@startuml
hide footbox
actor Utilisateur
participant "MainJavaFX" as Main
participant "ModeleMenu" as Modele
participant "VueTableau" as VueTableau
participant "ControleurColonneLigne" as Controleur
participant "CreationColonneFX" as CreationColonne

activate Main
Utilisateur -> Main: Lance l'application
create Modele
create VueTableau
Main -> VueTableau: Crée VueTableau avec Modele

activate VueTableau
Utilisateur -> VueTableau: Visualise l'interface

create Controleur
VueTableau -> Controleur: Crée ControleurColonneLigne

activate Controleur
Utilisateur -> Controleur: Clic sur '+ Ajouter une nouvelle colonne'
Controleur -> Modele: Appelle ControleurColonneLigne
Modele -> CreationColonne: Appelle CreationColonneFX

activate CreationColonne
Utilisateur -> CreationColonne: Remplit le nom de la colonne
CreationColonne -> Modele: Ajoute une nouvelle colonne
Modele -> VueTableau: Notifie la VueTableau

activate VueTableau
VueTableau -> VueTableau: Actualise l'affichage
Utilisateur -> VueTableau: Visualise la nouvelle colonne

@enduml