@startuml

skinparam class{
  BackgroundColor<<Iteration1>> Pink
  BorderColor<<Iteration1>> Black
}

skinparam class{
  BackgroundColor<<Iteration2>> LightBlue
  BorderColor<<Iteration2>> Black
}

class  CompositeTache <<Iteration1>> <<abstract>>{
  - id: int
  - nom: String
  - Description: String
  - LocalDate: Date
  - degreUrgence: int
  - tempsEstime: int
  - tacheRealise: boolean
  - DateDebutReal: LocalDate
  - dependance : Dependance

  + CompositeTache(String, int, int)
  + abstract ajouterSousTache(CompositeTache)) : void
  + abstract retirerSousTache(CompositeTache)) : void
  + getAttributs() : TypeAttributs
  + ajouterDependanceMere(CompositeTache) t) : void
  + ajouterDependanceFille(CompositeTache) t) : void
  + afficherDependance() : String
}

class SousTache <<Iteration1>> extends CompositeTache {
    + SousTache(id : int, String n, urgence: int, tempsEstime : int)
    + ajouterSousTache(CompositeTache : ct)) : boolean
    + retirerSousTache(id : int) : boolean
    + getSousTaches() : ArrayList<CompositeTache>
    + equals(Object obj) : boolean
}

class Tache <<Iteration1>> extends CompositeTache{
     + Tache(id : int, String n, urgence: int, tempsEstime : int)
     + ajouterSousTache(CompositeTache : ct)) : boolean
     + retirerSousTache(id : int) : boolean
     + equals(Object obj) : boolean
}

class Dependance <<Iteration1>> {
    + Dependance() : void
    + getTachesFilles() : ArrayList<(CompositeTache)>
    + getTachesMeres() : ArrayList<(CompositeTache)>
    + addDependanceFille(CompositeTache) ct) : void
    + addDependanceMeres(CompositeTache) ct) : void
    + afficherDependance(CompositeTache) ct) : String
}

class DiagrammeGantt extends ColonneLigne {
    + Gant(s : String), i : int) : void
 }

class ColonneLigne <<Iteration1>> {
  - numero: int
  - Nom: String

  + ColonneLigne(String, int)
  + ajouterTache(CompositeTache): void
  + supprimerTache(CompositeTache) : void
  + trierDate() : void
  + trierUrgence() : void
  + trierAlphabetique() : void
  + trouverTache(i : int) : void
  + getTacheList() : List<CompositeTache>
  + getNumero() : int
  + setNom(s : String) : void
}

interface Observateur {
  + actualiser(Sujet): void
}

class VueTache <<Iteration2>> implements Observateur {
  + VueTache(CompositeTache)
  + actualiser(Sujet): void
}

class VueBureau <<Iteration2>> implements Observateur {
  + int
  + VueBureau(ModeleMenu)
  + actualiser(Sujet): void
}

class VueBureauColonne <<Iteration2>> implements Observateur {
  + int
  + VueBureau(ModeleMenu)
  + actualiser(Sujet): void
}

class VueBureauLigne <<Iteration2>> implements Observateur {
  + int
  + VueBureau(ModeleMenu)
  + actualiser(Sujet): void
}

class VueColonne <<Iteration2>> implements Observateur {
  + int
  + VueColonne(ArrayList<CompositeTache>, ModeleMenu, int)
  + actualiser(Sujet): void
}

class VueListe implements Observateur {
  + VueListe(ModeleMenu)
  + actualiser(Sujet): void
}

class VueArchive implements Observateur {
  + VueArchive(ModeleMenu)
  + actualiser(Sujet): void
}

class VueGantt implements Observateur {
  + VueGantt(ModeleMenu)
  + actualiser(Sujet): void
}

class ControleurTache {
  + ControleurTache(ModeleMenu)
  + handle(ActionEvent): void
}

class ControleurBoutonMenu{
  + ControleurBoutonMenu(ModeleMenu)
  + handle(ActionEvent): void
}

class ControleurColonneLigne{
  + ControleurColonneLigne(ModeleMenu)
  + handle(ActionEvent): void
}

class ControleurSelectionTache{
  + ControleurSelectionTache(ModeleMenu)
  + handle(ActionEvent): void
}

class ControleurAjoutTache <<Iteration2>>{
  + ControleurAjoutTache(ModeleMenu)
  + handle(ActionEvent): void
}

class ControleurAjoutColonne <<Iteration2>>{
  + ControleurAjoutColonne(ModeleMenu)
  + handle(ActionEvent): void
}

class ModeleMenu <<Iteration1>> implements Sujet {
  + nbColonnes : int
  + tacheCompositeNumId : int

  + ModeleMenu()
  + ajouterColonneLigne() : void
  + ajouterCompositeTache(int, (CompositeTache) ct) : void
  + deplacerCompositeTache(idColonneLigne : int, idNewColonneLigne : int, CompositeTache ct) : void
  + trierColonneLigne(idColonne: int, typeTri: String) : void
  + afficherListe() : void
  + afficherColonne() : void
  + afficherGant() : void
  + archiverToutesTache(idColonneLigne : int) : void
  + archiverTache(idColonneLigne : int, idTache : int) : void
  + supprimerTache(idColonneLigne : int), idTache: int) : void
  + supprimerColonneLigne(idColonneLigne : int)): void
  + ajouterObservateur(Observateur): void
  + supprimerObservateur(Observateur) : void
  + notifierObservateurs(): void
}

interface StrategyAffichage {
}

class StrategyColonne implements StrategyAffichage {
  + StrategyColonne()
}

class StrategyLigne implements StrategyAffichage {
  + StrategyLigne()
}

class Archive extends ColonneLigne {
  - Singleton()
  + getInstance():Archive
}


ModeleMenu "affichages"---> "1" StrategyAffichage
ModeleMenu "archive"---> "1" Archive
ModeleMenu "observateurs"--down-> "0..*" Observateur : observateurs
ModeleMenu "colonnesLignes"--left-> "0..*" ColonneLigne
ColonneLigne  "\n\n\n\n+ tachesComposites" ---> "0..*"CompositeTache
CompositeTache -left--> "0..*" CompositeTache
CompositeTache "dependance" -left--> "0..1" Dependance
Dependance "tachesMere" -right--> "0..*" CompositeTache
Dependance "tachesFilles" --right--> "0..*" CompositeTache
Archive "instance"---> "1" Archive
SousTache -right--> "0..*"CompositeTache
ControleurTache --> "0..1" ModeleMenu
ControleurAjoutColonne --> "0..1" ModeleMenu
ControleurAjoutTache --> "0..1" ModeleMenu
ControleurBoutonMenu --> "0..1" ModeleMenu
ControleurColonneLigne --> "0..1" ModeleMenu
ControleurSelectionTache --> "0..1" ModeleMenu
VueColonne --> "0..*"CompositeTache
VueArchive --> "1"ModeleMenu
VueGantt --> "1"ModeleMenu
VueListe --> "1"ModeleMenu
VueBureau --> "1"ModeleMenu
VueBureauColonne --> "1"ModeleMenu
VueBureauLigne --> "1"ModeleMenu
VueTache --> "1"ModeleMenu


@enduml
